name: kanjika

services:
  db:
    image: postgres:17.2
    container_name: kanjika-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kanjika_network

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kanjika-api
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5039:5039"
      - "7161:7161"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kanjika_network

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: kanjika-web
    ports:
      - "5173:5173"
    depends_on:
      - api


volumes:
  postgres_data:

networks:
  kanjika_network:
    name: kanjika_network