name: kanjika

services:
  db:
    image: postgres:17.2
    container_name: kanjika-db
    environment:
      - POSTGRES_DB=KanjiKaDb
      - POSTGRES_USER=kanjika_admin
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanjika_admin -d KanjiKaDb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: