name: kanjika-dev

services:
  db:
    image: postgres:17.2
    container_name: kanjika-dev-db
    profiles:
      - dev
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanjika_dev_network


volumes:
  postgres_data:

networks:
  kanjika_dev_network:
    name: kanjika_dev_network