// <auto-generated />
using System;
using KanjiKa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KanjiKa.Data.Migrations
{
    [DbContext(typeof(KanjiKaDbContext))]
    [Migration("20260405091539_AddReadingSystem")]
    partial class AddReadingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KanjiKa.Domain.Entities.Grammar.GrammarExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english");

                    b.Property<int>("GrammarPointId")
                        .HasColumnType("integer")
                        .HasColumnName("grammar_point_id");

                    b.Property<string>("Japanese")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("japanese");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading");

                    b.HasKey("Id")
                        .HasName("pk_grammar_examples");

                    b.HasIndex("GrammarPointId")
                        .HasDatabaseName("ix_grammar_examples_grammar_point_id");

                    b.ToTable("grammar_examples", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Grammar.GrammarExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<string>("Distractor1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distractor1");

                    b.Property<string>("Distractor2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distractor2");

                    b.Property<string>("Distractor3")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distractor3");

                    b.Property<int>("GrammarPointId")
                        .HasColumnType("integer")
                        .HasColumnName("grammar_point_id");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sentence");

                    b.HasKey("Id")
                        .HasName("pk_grammar_exercises");

                    b.HasIndex("GrammarPointId")
                        .HasDatabaseName("ix_grammar_exercises_grammar_point_id");

                    b.ToTable("grammar_exercises", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Grammar.GrammarPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<int>("JlptLevel")
                        .HasColumnType("integer")
                        .HasColumnName("jlpt_level");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_grammar_points");

                    b.ToTable("grammar_points", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Grammar.GrammarProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<int>("GrammarPointId")
                        .HasColumnType("integer")
                        .HasColumnName("grammar_point_id");

                    b.Property<DateTimeOffset>("LastPracticedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_practiced_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_grammar_proficiencies");

                    b.HasIndex("GrammarPointId")
                        .HasDatabaseName("ix_grammar_proficiencies_grammar_point_id");

                    b.HasIndex("UserId", "GrammarPointId")
                        .IsUnique()
                        .HasDatabaseName("ix_grammar_proficiencies_user_id_grammar_point_id");

                    b.ToTable("grammar_proficiencies", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kana.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Romanization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("romanization");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kana.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Romanization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("romanization");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id")
                        .HasName("pk_examples");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_examples_character_id");

                    b.ToTable("examples", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kana.Proficiency", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LastPracticed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_practiced");

                    b.Property<DateTimeOffset>("LearnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("learned_at");

                    b.Property<DateTimeOffset?>("NextReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_date");

                    b.Property<int>("SrsStage")
                        .HasColumnType("integer")
                        .HasColumnName("srs_stage");

                    b.HasKey("UserId", "CharacterId")
                        .HasName("pk_proficiencies");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_proficiencies_character_id");

                    b.ToTable("proficiencies", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kanji.Kanji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("character");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<int>("JlptLevel")
                        .HasColumnType("integer")
                        .HasColumnName("jlpt_level");

                    b.Property<string>("KunyomiReading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kunyomi_reading");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("OnyomiReading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("onyomi_reading");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer")
                        .HasColumnName("stroke_count");

                    b.HasKey("Id")
                        .HasName("pk_kanjis");

                    b.ToTable("kanjis", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kanji.KanjiExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id")
                        .HasName("pk_kanji_examples");

                    b.HasIndex("KanjiId")
                        .HasDatabaseName("ix_kanji_examples_kanji_id");

                    b.ToTable("kanji_examples", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kanji.KanjiProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KanjiId")
                        .HasColumnType("integer")
                        .HasColumnName("kanji_id");

                    b.Property<DateTimeOffset>("LearnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("learned_at");

                    b.Property<DateTimeOffset?>("NextReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_date");

                    b.Property<int>("SrsStage")
                        .HasColumnType("integer")
                        .HasColumnName("srs_stage");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_kanji_proficiencies");

                    b.HasIndex("KanjiId")
                        .HasDatabaseName("ix_kanji_proficiencies_kanji_id");

                    b.HasIndex("UserId", "KanjiId")
                        .IsUnique()
                        .HasDatabaseName("ix_kanji_proficiencies_user_id_kanji_id");

                    b.ToTable("kanji_proficiencies", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Learning.LessonCompletion", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.HasKey("UserId", "CharacterId")
                        .HasName("pk_lesson_completions");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_lesson_completions_character_id");

                    b.ToTable("lesson_completions", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Path.LearningUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_learning_units");

                    b.ToTable("learning_units", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Path.UnitContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentId")
                        .HasColumnType("integer")
                        .HasColumnName("content_id");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer")
                        .HasColumnName("content_type");

                    b.Property<int>("LearningUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_unit_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_unit_contents");

                    b.HasIndex("LearningUnitId")
                        .HasDatabaseName("ix_unit_contents_learning_unit_id");

                    b.ToTable("unit_contents", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Path.UnitProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("BestScore")
                        .HasColumnType("integer")
                        .HasColumnName("best_score");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<int>("LearningUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_unit_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_unit_progresses");

                    b.HasIndex("LearningUnitId")
                        .HasDatabaseName("ix_unit_progresses_learning_unit_id");

                    b.HasIndex("UserId", "LearningUnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_progresses_user_id_learning_unit_id");

                    b.ToTable("unit_progresses", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Path.UnitTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentType")
                        .HasColumnType("integer")
                        .HasColumnName("content_type");

                    b.Property<char>("CorrectOption")
                        .HasColumnType("character(1)")
                        .HasColumnName("correct_option");

                    b.Property<int>("LearningUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_unit_id");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_a");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_b");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_c");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_d");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_unit_tests");

                    b.HasIndex("LearningUnitId")
                        .HasDatabaseName("ix_unit_tests_learning_unit_id");

                    b.ToTable("unit_tests", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Reading.ComprehensionQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char>("CorrectOption")
                        .HasColumnType("character(1)")
                        .HasColumnName("correct_option");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_a");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_b");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_c");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_d");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("ReadingPassageId")
                        .HasColumnType("integer")
                        .HasColumnName("reading_passage_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_comprehension_questions");

                    b.HasIndex("ReadingPassageId")
                        .HasDatabaseName("ix_comprehension_questions_reading_passage_id");

                    b.ToTable("comprehension_questions", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Reading.ReadingPassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("JlptLevel")
                        .HasColumnType("integer")
                        .HasColumnName("jlpt_level");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_reading_passages");

                    b.ToTable("reading_passages", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Reading.ReadingProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<int>("ReadingPassageId")
                        .HasColumnType("integer")
                        .HasColumnName("reading_passage_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reading_proficiencies");

                    b.HasIndex("ReadingPassageId")
                        .HasDatabaseName("ix_reading_proficiencies_reading_passage_id");

                    b.HasIndex("UserId", "ReadingPassageId")
                        .IsUnique()
                        .HasDatabaseName("ix_reading_proficiencies_user_id_reading_passage_id");

                    b.ToTable("reading_proficiencies", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_code");

                    b.Property<DateTimeOffset?>("PasswordResetExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expiry");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Grammar.GrammarExample", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Grammar.GrammarPoint", "GrammarPoint")
                        .WithMany("Examples")
                        .HasForeignKey("GrammarPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grammar_examples_grammar_points_grammar_point_id");

                    b.Navigation("GrammarPoint");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Grammar.GrammarExercise", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Grammar.GrammarPoint", "GrammarPoint")
                        .WithMany("Exercises")
                        .HasForeignKey("GrammarPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grammar_exercises_grammar_points_grammar_point_id");

                    b.Navigation("GrammarPoint");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Grammar.GrammarProficiency", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Grammar.GrammarPoint", "GrammarPoint")
                        .WithMany()
                        .HasForeignKey("GrammarPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grammar_proficiencies_grammar_points_grammar_point_id");

                    b.HasOne("KanjiKa.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grammar_proficiencies_users_user_id");

                    b.Navigation("GrammarPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kana.Example", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Kana.Character", "Character")
                        .WithMany("Examples")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_examples_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kana.Proficiency", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Kana.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proficiencies_characters_character_id");

                    b.HasOne("KanjiKa.Domain.Entities.Users.User", "User")
                        .WithMany("Proficiencies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proficiencies_users_user_id");

                    b.Navigation("Character");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kanji.KanjiExample", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Kanji.Kanji", "Kanji")
                        .WithMany("Examples")
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kanji_examples_kanjis_kanji_id");

                    b.Navigation("Kanji");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kanji.KanjiProficiency", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Kanji.Kanji", "Kanji")
                        .WithMany()
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kanji_proficiencies_kanjis_kanji_id");

                    b.HasOne("KanjiKa.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kanji_proficiencies_users_user_id");

                    b.Navigation("Kanji");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Learning.LessonCompletion", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Kana.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_completions_characters_character_id");

                    b.HasOne("KanjiKa.Domain.Entities.Users.User", "User")
                        .WithMany("LessonCompletions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_completions_users_user_id");

                    b.Navigation("Character");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Path.UnitContent", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Path.LearningUnit", "LearningUnit")
                        .WithMany("Contents")
                        .HasForeignKey("LearningUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_contents_learning_units_learning_unit_id");

                    b.Navigation("LearningUnit");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Path.UnitProgress", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Path.LearningUnit", "LearningUnit")
                        .WithMany()
                        .HasForeignKey("LearningUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_progresses_learning_units_learning_unit_id");

                    b.HasOne("KanjiKa.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_progresses_users_user_id");

                    b.Navigation("LearningUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Path.UnitTest", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Path.LearningUnit", "LearningUnit")
                        .WithMany("Tests")
                        .HasForeignKey("LearningUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_tests_learning_units_learning_unit_id");

                    b.Navigation("LearningUnit");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Reading.ComprehensionQuestion", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Reading.ReadingPassage", "ReadingPassage")
                        .WithMany("Questions")
                        .HasForeignKey("ReadingPassageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comprehension_questions_reading_passages_reading_passage_id");

                    b.Navigation("ReadingPassage");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Reading.ReadingProficiency", b =>
                {
                    b.HasOne("KanjiKa.Domain.Entities.Reading.ReadingPassage", "ReadingPassage")
                        .WithMany()
                        .HasForeignKey("ReadingPassageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_proficiencies_reading_passages_reading_passage_id");

                    b.HasOne("KanjiKa.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_proficiencies_users_user_id");

                    b.Navigation("ReadingPassage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Grammar.GrammarPoint", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kana.Character", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Kanji.Kanji", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Path.LearningUnit", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Reading.ReadingPassage", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("KanjiKa.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("LessonCompletions");

                    b.Navigation("Proficiencies");
                });
#pragma warning restore 612, 618
        }
    }
}
