name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build, Test, and Analyze
    runs-on: windows-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------- Client (frontend) ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Run client tests with coverage (Vitest)
        working-directory: client
        run: npm run test:coverage -- --run

      # ---------- Server (backend) ----------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build server
        run: dotnet build .\server\KanjiKa.sln --configuration Release

      - name: Run server tests with coverage (OpenCover)
        run: |
          dotnet test .\server\KanjiKa.sln `
            --logger trx `
            --results-directory .\server\TestResults `
            --collect:"XPlat Code Coverage" `
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Publish .NET test results
        uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
        if: success() || failure()
        with:
          name: Unit Tests
          path: server/TestResults/*.trx
          reporter: dotnet-trx

      # ---------- Upload coverage artifacts ----------
      - name: Upload client coverage (lcov)
        uses: actions/upload-artifact@v4
        with:
          name: client-coverage
          path: client/coverage/lcov.info
          if-no-files-found: error

      - name: Upload server coverage (OpenCover)
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: server/TestResults/**/coverage.opencover.xml
          if-no-files-found: error
