name: SonarQube

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  analyze:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Download coverage and analyze on Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download client coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: client-coverage
          path: client/coverage
          run-id: ${{ github.event.workflow_run.id }}

      - name: Download server coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: server-coverage
          path: server/TestResults
          run-id: ${{ github.event.workflow_run.id }}

      - name: Verify downloaded coverage files
        run: |
          ls -la client/coverage || true
          ls -la server/TestResults || true

      - name: Analyze with SonarQube (Linux)
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
